import * as path from "path";
import * as os from "os";
import { registerWagerTools } from "./src/tools";
import { resolveStorePath } from "./src/watcher";

const DEFAULT_WALLET = path.join(os.homedir(), ".config", "solana", "id.json");
const DEFAULT_RPC = "https://api.devnet.solana.com";
const DEFAULT_PROGRAM_ID = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS";
const DEFAULT_STORE = path.join(os.homedir(), ".openclaw", "sol-wager", "pending.json");

export function activate(openclaw: any): void {
  const pluginCfg = (openclaw.config?.plugins?.["sol-wager"] ?? {}) as Record<string, string>;

  const walletPath = resolveStorePath(
    pluginCfg.walletPath ?? process.env.SOLANA_WALLET_PATH ?? DEFAULT_WALLET
  );
  const rpcUrl = pluginCfg.rpcUrl ?? process.env.SOLANA_RPC_URL ?? DEFAULT_RPC;
  const programId = pluginCfg.programId ?? process.env.SOL_WAGER_PROGRAM_ID ?? DEFAULT_PROGRAM_ID;
  const storePath = resolveStorePath(
    pluginCfg.storePath ?? process.env.SOL_WAGER_STORE_PATH ?? DEFAULT_STORE
  );

  // IDL is generated by `anchor build` → target/idl/sol_wager.json
  // Copy it here before running: cp ../target/idl/sol_wager.json ./idl.json
  let idl: object;
  try {
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    idl = require("./idl.json");
  } catch {
    throw new Error(
      "[sol-wager] idl.json not found. Run `anchor build` from the repo root, " +
        "then copy target/idl/sol_wager.json to skill/idl.json"
    );
  }

  const cfg = { walletPath, rpcUrl, programId, storePath, idl };
  const tools = registerWagerTools(cfg);

  for (const [name, tool] of Object.entries(tools)) {
    openclaw.registerTool(name, tool);
  }
}

export function deactivate(_openclaw: any): void {
  // No persistent resources to clean up
}
